### ISSUE TITLE
Dataset Split

### ISSUE THREAD

**Issue by zhongcl-thu** [qq456cvb/UKPGAN#1]
Hello, thanks for your sharing. It's a nice job. 
Can you share the dataset split file? I can not find the 'train/val/test.txt'.

**Comment by qq456cvb** [comment]
Thanks for your interest. We use the split file from KeypointNet dataset. You can find them at https://github.com/qq456cvb/KeypointNet/tree/master/splits. Feel free if you have any other questions.

**Comment by zhongcl-thu** [comment]
Thanks, I got the split file. Is the pointcloud in the KeypointNet normalized to [-0.5, 0.5]?  In the ModelNet40 dataset, the input is scaled to [-1, 1].

**Comment by qq456cvb** [comment]
The point cloud is sampled directly from ShapeNet mesh, which uses the normalization strategy described [here](https://shapenet.org/qaforum/index.php?qa=75&qa_1=whats-the-normalization-method-of-shapenetcore-v2).

**Comment by zhongcl-thu** [comment]
Thanks, I will check the normalization strategy. But what is the 'sdv_cache'? I cannot find it which is used in eval_iou.py.

**Comment by qq456cvb** [comment]
It's used in dataloader. Computing sdv features is time-consuming, to avoid computing it each time a point cloud is loaded, we optionally cache them on disk.
