### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_sdv)

### ISSUE THREAD

**Issue by zhongcl-thu** [qq456cvb/UKPGAN#2]
Hi, I met the problem when evaluating the pretrained model on KeypointNet ('python eval_iou.py'). It indicates that 'sdv' can not be imported but I successfully 'cmake/make' the 'sdv' and get the 'sdv.cpython-36m-x86_64-linux-gnu.so' in the 'build' folder. My environment is Ubuntu OS, python3.6.  

<img width="712" alt="image" src="https://user-images.githubusercontent.com/37363660/163905623-919d1ee3-aed5-4e11-ad04-ac48a2b65efb.png">

**Comment by qq456cvb** [comment]
This is quite strange, and I have no idea how it happens. Could you try compiling a simple pybind11 program to see if your pybind11 installation is ok? https://pybind11.readthedocs.io/en/stable/basics.html#creating-bindings-for-a-simple-function

**Comment by zhongcl-thu** [comment]
After recompiling the PCL, the problem is solved. Thanks!
