### ISSUE TITLE
hyper-parameters of conventional 3D keypoint detectors

### ISSUE THREAD

**Issue by zhongcl-thu** [qq456cvb/UKPGAN#3]
Can you give the hyper-parameters of the conventional 3D keypoint detectors (SIFT-3D, HARRIS-3D, ISS) in your experiments? Thanks.

**Comment by qq456cvb** [comment]
We follow the same hyperparameters as that in USIP. You can find them at https://github.com/lijx10/USIP/blob/master/evaluation/save_keypoints.py.

**Comment by zhongcl-thu** [comment]
Thank you.
