### ISSUE TITLE
How to train the 'universal' model on ShapeNet?

### ISSUE THREAD

**Issue by zhongcl-thu** [qq456cvb/UKPGAN#4]
'The 'universal' model is trained on a large collection of ShapeNet models (across 10+ categories).' Does that mean the universal model is trained on the KeypointNet dataset (16 categories)?  I cannot find the implementation of that.

**Comment by qq456cvb** [comment]
"Does that mean the universal model is trained on the KeypointNet dataset (16 categories)" Yes.
It should be relatively easy to modify the ShapeNetDataFlow to load all the point clouds from all the 16 categories.

**Comment by zhongcl-thu** [comment]
Thanks.
