### ISSUE TITLE
SMPL model

### ISSUE THREAD

**Issue by zhongcl-thu** [qq456cvb/UKPGAN#6]
What is the version of SMPL in your paper? '**version 1.0.0** for Python 2.7 (**10** shape PCs)' or '**version 1.1.0** for Python 2.7 (male, female, neutral all with **300 shape** PCs)'. Thanks.

**Comment by qq456cvb** [comment]
We use the SMPL model at https://github.com/CalciferZh/SMPL, which generates SMPL models on the fly by tuning pose parameters.

**Comment by zhongcl-thu** [comment]
Thanks. Would you like to share the test code for SMPL?

**Comment by qq456cvb** [comment]
We are still organizing the code of this part, and will upload it once I've got time. The core logic is shown below.



            for i in range(2):
                pose = (np.random.rand(*smpl.pose_shape) - 0.5) * 0.4
                beta = (np.random.rand(*smpl.beta_shape) - 0.5) * 0.06
                trans = np.zeros(smpl.trans_shape)
                smpl.set_params(beta=beta, pose=pose, trans=trans)
                
                if i == 0:
                    pc, _, idx, u, v = sample_vertex_from_mesh(smpl.verts, smpl.faces, num_samples=cfg.num_points)
                else:
                    pc, _, _, _, _ = sample_vertex_from_mesh(smpl.verts, smpl.faces, rnd_idxs=idx, u=u, v=v, num_samples=cfg.num_points)
                pc_feature = np.array(sdv.compute(pc)).astype(np.float32)

                output = predictor(pc[None], pc_feature[None])
                    
                z = output[0][0]
                
                idx = np.where(z > 0.5)[0]
                kp = pc[z > 0.5]
                num_kps += len(kp)
                
                if i == 0:
                    template_idx = pairwise_distances_argmin(kp, pc)
                    
                    labels = np.ones((pc.shape[0]), np.int)
                    labels[np.array(template_idx)] = 2
                    
                    template_idx = set(template_idx)
                else:
                    template_idx2 = pairwise_distances_argmin(kp, pc)
                    
                    transferred_points = pc[list(template_idx)]
                    _, dist = pairwise_distances_argmin_min(transferred_points, pc[template_idx2])
                    
                    template_idx2 = set(template_idx2)
                    
                    iou = len(template_idx & template_idx2) / (len(template_idx | template_idx2))
                    ious += iou
                    dists += np.mean(dist)
                    
        print('{} keypoints: iou {:.4f}, dist {:.4f}'.format(desired_keypoint_num, ious / num_exp, dists / num_exp))

**Comment by zhongcl-thu** [comment]
Thanks!
